### ISSUE TITLE
./instal.sh GID error

### ISSUE THREAD

**Issue by nyok92** [immstudios/nebula-demo#1]
Hi, i've got this error with ./install.sh script when building docker images.

addgroup: The GID `0' is already in use.
ERROR: Service 'core' failed to build: The command '/bin/sh -c addgroup --gid $GROUP_ID user' returned a non-zero code: 1

Tried to force UID and GID to 1000 inside insatll.sh, docker build successfully.
But then with ./setup.py inside core container i've got permission issues with mkdir (cs)...

Any idea ?
Thanks

**Comment by martastain** [comment]
This happens, when you start the stack as root... Dockerfile tries to create the same user you are using on the host, but it cannot recreate root. I did it this way in order to preserve permisions on the mounted volume and I am not sure, what would be the best way to do it. Maybe running the stack as root is better since the container should be able to mount remote storages as well... - in that case, you can just get rid of the lines 3-8 in nebula/Dockerfile but i am open to discussion.

**Comment by martastain** [comment]
I've removed the nebula user, so the problem is now moved to the mounted volume, which - in case the stack is running as non-root user / causes that files created by nebula are not writable. But i guess this is the lesser of two evils.
